# Generated by Django 6.0.3 on 2026-04-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallpaper', models.ImageField(blank=True, null=True, upload_to='wallpapers/')),
                ('overlay_opacity', models.FloatField(default=0.7)),
                ('site_title', models.CharField(default='Aether', max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('github_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
